Databases:
  AMI: ./amicorpus/*/audio/{uri}.wav
  MUSAN: ./musan/{uri}.wav
  VOXCON: /home/jovyan/work/voxsrc21-dia/data/voxconverse/sample/{uri}.wav
  # VOXCON: /app/datasets/voxsrc21/dev/wav/{uri}.wav
  VOXSRC21: /app/datasets/voxsrc21/workshop-test/wav/{uri}.wav

Protocols:
  VOXCON:
    SpeakerDiarization:
      Sample:
        train:
          uri: ../lists/voxconverse/sample/train.lst
          annotation: ../lists/voxconverse/sample/train.rttm
          annotated: ../lists/voxconverse/sample/train.uem
        development:
          uri: ../lists/voxconverse/sample/dev.lst
          annotation: ../lists/voxconverse/sample/dev.rttm
          annotated: ../lists/voxconverse/sample/dev.uem
      VoxConverse:
        development:
          uri: /app/datasets/voxsrc21/dev/dev.lst
          annotation: /app/datasets/voxsrc21/dev/rttm/{uri}.rttm
          # annotated: /app/datasets/voxsrc21/dev/uem/{uri}.uem
        test:
          uri: /app/datasets/voxsrc21/test/test.lst
          annotation: /app/datasets/voxsrc21/test/rttm/{uri}.rttm
          # annotated: /app/datasets/voxsrc21/test/uem/{uri}.uem
  VOXSRC21:
    SpeakerDiarization:
      Challenge:
        test:
          uri: /app/datasets/voxsrc21/workshop-test/workshop-test.lst
          # annotation: /app/datasets/voxsrc21/workshop-test/rttm/{uri}.rttm
          # annotated: /app/datasets/voxsrc21/workshop-test/uem/{uri}.uem

  AMI:
    SpeakerDiarization:
      MixHeadset:
        train:
          uri: ./AMI/MixHeadset.train.lst
          annotation: ./AMI/MixHeadset.train.rttm
          annotated: ./AMI/MixHeadset.train.uem
        development:
          uri: ./AMI/MixHeadset.development.lst
          annotation: ./AMI/MixHeadset.development.rttm
          annotated: ./AMI/MixHeadset.development.uem
        test:
          uri: ./AMI/MixHeadset.test.lst
          annotation: ./AMI/MixHeadset.test.rttm
          annotated: ./AMI/MixHeadset.test.uem
  MUSAN:
    Collection:
      BackgroundNoise:
        uri: ./MUSAN/background_noise.txt
      Noise:
        uri: ./MUSAN/noise.txt
      Music:
        uri: ./MUSAN/music.txt
      Speech:
        uri: ./MUSAN/speech.txt
